# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hcarrasc <hcarrasc@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/27 11:11:21 by hcarrasc          #+#    #+#              #
#    Updated: 2023/10/27 13:04:05 by hcarrasc         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

OBJ = $(SRC:.cpp=.o)
CC = c++
RM = rm -f
CPPFLAGS = -Wall -Wextra -Werror -std=c++98 -pedantic
SRC = 	main.cpp				\
		Animal.cpp				\
		Dog.cpp					\
		Cat.cpp					\
		WrongCat.cpp			\
		WrongAnimal.cpp			\
		
NAME = Animals

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CPPFLAGS) $(OBJ) -o $(NAME)

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean $(NAME)

.PHONY: all clean fclean re